Feature integrating ros lift ctrl with wrp ros
westonrobot/wrp_ros pull request #1
Opened 2024-02-19 10:18 UTC by Timothylee1

Modified the src/peripheral/README.md, included action and service files, and lift_server_node .hpp and .cpp.
Removed the lift_client_node .hpp and .cpp.

2024-02-20 01:59 UTC, hanskw-weston requested changes

2024-02-20 01:59 UTC, hanskw-weston commented on CMakeLists.txt
> +# target_link_libraries(lift_client_node ${catkin_LIBRARIES})
Please remove these comments

2024-02-20 01:59 UTC, hanskw-weston commented on include/wrp_ros/peripheral/lift_server_node.hpp
> +
This should not be called ActionServer. Should be called LiftControllerNode.

2024-02-20 01:59 UTC, hanskw-weston commented on include/wrp_ros/peripheral/lift_server_node.hpp
This file should be called lift_controller_node.hpp

2024-02-20 01:59 UTC, hanskw-weston commented on include/wrp_ros/peripheral/lift_server_node.hpp
> +  bool SrvCB(wrp_ros::LiftQuery::Request& req,
Name should be more descriptive. 
```suggestion
  bool QueryCallback(wrp_ros::LiftQuery::Request& req,
```

2024-02-20 01:59 UTC, hanskw-weston commented on src/peripheral/README.md
> +| `device_path` | char*  | Path to microcontroller port.                                 |
```suggestion
| `device_path` | char*  | Path to lift controller port.                                 |
```

2024-02-20 01:59 UTC, hanskw-weston commented on include/wrp_ros/peripheral/lift_server_node.hpp
> +  }
Implementation should not be in hpp file but in cpp file

2024-02-20 01:59 UTC, hanskw-weston commented on src/peripheral/lift_server_node.cpp
> +  liftController_.Connect(device_path, baud_rate);
You specified in readme that device_path and baud_rate are ROS parameters but are not actually exposing these as parameters.

2024-02-20 08:36 UTC, hanskw4267 commented on include/wrp_ros/peripheral/lift_controller_node.hpp
> +  westonrobot::LiftController liftController_;
names should follow the style guide

```suggestion
  ros::ServiceServer query_server_;
  actionlib::SimpleActionServer<wrp_ros::LiftControlAction> lift_control_server_;
  westonrobot::LiftController lift_controller_;
```

2024-02-20 08:47 UTC, hanskw-weston requested changes

2024-02-20 08:47 UTC, hanskw-weston commented on include/wrp_ros/peripheral/lift_controller_node.hpp
> +  westonrobot::LiftController liftController_;
names should follow the style guide

```suggestion
  ros::ServiceServer query_server_;
  actionlib::SimpleActionServer<wrp_ros::LiftControlAction> lift_control_server_;
  westonrobot::LiftController lift_controller_;
```

2024-02-20 08:47 UTC, hanskw-weston commented on src/peripheral/lift_controller_node.cpp
> +}
Maybe move the Server_ below the connect. There is a case here that a action goal arrives before you connect to the lift successfully.

```suggestion
      {
  if (!ReadParameters()) {
    ROS_ERROR("Could not load parameters");
    ros::shutdown();
  }

  liftController_.Connect(device_path_, baud_rate_);
  if (!liftController_.IsOkay()) {
    std::cerr << "Failed to connect to lift controller" << std::endl;
    ros::shutdown();
  }

  srvServer_ = nh_.advertiseService("/lift_controller/service",
                                    &LiftControllerNode::QueryCallback, this);
                                   
  Server_ = actionlib::SimpleActionServer<wrp_ros::LiftControlAction>(
      nh_, "lift_controller_action",
      [this](const wrp_ros::LiftControlGoalConstPtr& goal) {
        this->LiftControllerCallback(goal);
      },
      false);
  Server_.start(); 
}
```

2024-02-20 08:47 UTC, hanskw-weston commented on src/peripheral/README.md
> +| `/lift_controller/service`| wrp_ros::LiftQuery | Query for state of the provided lift id. |
Please add the action into the readme and maybe rename the service and action topics to be more descriptive

maybe 

/lift_controller/state_query
/lift_controller/goal

2024-03-22 05:50 UTC, karthee-weston commented on action/LiftControl.action
> +uint8 id
Include comments to detail which id number corresponds to which lift.

2024-03-22 06:58 UTC, karthee-weston approved these changes
LGTM

2024-03-22 06:59 UTC, karthee-weston approved these changes
LGTM

2024-03-22 07:00 UTC, karthee-weston approved these changes
LGTM

2024-03-22 07:00 UTC, merged